myboot:
  name: Dev Env

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/boot_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: Host
    password: maria

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중엔 update, 배포 시엔 none 권장
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    root: debug
    com.devdiary: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

  file:
    name: logs/dev.log

  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
